### ISSUE TITLE
[meta] project todos, status, issues

### ISSUE THREAD

**Issue by ctcpip** [ctcpip/jquery-security-patches#4]
# EOL jQuery security project

## updating jQuery

> [!NOTE]
> reviewers needed for jQuery code changes, especially where patch was not sourced from future jQuery versions.  also assess whether any additional unit tests are needed.

- [x] https://github.com/ctcpip/jquery-security-patches/pull/2
- [x] https://github.com/ctcpip/jquery-security-patches/pull/3
  - can't run jQuery QUnit tests yet, but [A/B tests pass](https://github.com/ctcpip/jquery-security-patches/actions/runs/7912336070/job/21597920194#step:7:558)
- [ ] fix all CVEs in `1.4.4`
- [ ] fix all CVEs in `1.5.2`
- [x] https://github.com/ctcpip/jquery-security-patches/pull/1
- [ ] fix all CVEs in `1.7.2`
- [ ] fix all CVEs in `1.8.3`
- [ ] fix all CVEs in `1.12.4`
- [ ] fix all CVEs in `2.2.4`

## A/B CVE testing

> [!NOTE]
> reviewers needed for reproduction code, especially where [CVEs were not reproducible with certain jQuery versions](https://github.com/ctcpip/jquery-security-patches/#:~:text=CVE%2D2015%2D9251%20is%20not%20reproducible)

[reproduction code is here](https://github.com/ctcpip/jquery-security-patches/blob/main/security/site/main.mjs#L195)

- [ ] CVE-2011-4969
- [ ] CVE-2012-6708
- [ ] CVE-2015-9251
- [ ] CVE-2019-11358
- [ ] CVE-2020-7656
- [ ] CVE-2020-11022
- [ ] CVE-2020-11023
- [ ] CVE-2020-23064
